//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maui.FinancialManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maui.FinancialManager.Resources.SearchUrls", typeof(SearchUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;operationName&quot;:&quot;Search&quot;,&quot;variables&quot;:{&quot;searchInput&quot;:{&quot;term&quot;:&quot;!searchTerm!&quot;,&quot;pagination&quot;:{&quot;page&quot;:0,&quot;window&quot;:10},&quot;stixAcceleratorId&quot;:null,&quot;enableMarketplace&quot;:true,&quot;searchApiVersion&quot;:&quot;LINX&quot;,&quot;branchIdBranchStockId&quot;:null}},&quot;query&quot;:&quot;query Search($searchInput: SearchInput!, $isStixNewAccelerator: Boolean, $token: String) {\n  search(search: $searchInput, token: $token, isStixNewAccelerator: $isStixNewAccelerator) {\n    ...SearchResult\n    __typename\n  }\n}\n\nfragment SearchResult on SearchResult {\n  sorts {\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrogaRaia {
            get {
                return ResourceManager.GetString("DrogaRaia", resourceCulture);
            }
        }
    }
}
