FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 5095
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /
COPY ["FinancialManager.Api/FinancialManager.Api.csproj", "FinancialManager.Api/"]
COPY ["FinancialManager.Commons/FinancialManager.Commons.csproj", "FinancialManager.Commons/"]
COPY ["FinancialManager.Data/FinancialManager.Data.csproj", "FinancialManager.Data/"]
RUN dotnet restore "FinancialManager.Api/FinancialManager.Api.csproj"
COPY . .
WORKDIR "/"
RUN dotnet build "FinancialManager.Api/FinancialManager.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FinancialManager.Api/FinancialManager.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FinancialManager.Api.dll"]